# Remove the "-DSHOW_LOG_ERROR" to eliminate the
# verbose error logging messages generated by EZNet
CFLAGS=-g -std=gnu11 -fsanitize=address -Wall -Werror -DSHOW_LOG_ERROR 

all: webserver

webserver: webserver.c eznet.o httpResponse.o utils.o
	$(CC) $(CFLAGS) -owebserver webserver.c eznet.o httpResponse.o utils.o -lbsd

httpResponse.o: httpResponse.c httpResponse.h utils.c utils.h
	$(CC) -c $(CFLAGS) httpResponse.c utils.c utils.h -lbsd

utils.o: utils.c utils.h
	$(CC) -c $(CFLAGS) utils.c

eznet.o: eznet.c eznet.h
	$(CC) -c $(CFLAGS) eznet.c

clean:
	rm webserver *.o

